the task page can show all the tasks from database
error: task page only show todo list, doesn't show complete list.
the reason is, unable to show two listviews. 
solution is to use scrollview or recycle view. need change task_fragment.java/xml coding. 
reference:
http://www.devexchanges.info/2015/05/android-tip-combining-multiple.html
http://www.devexchanges.info/2017/01/populating-multiple-list-views-on.html